# Generated by Django 4.2.15 on 2024-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
